name: Counters

on: [push]

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        COUNT=$(jq  '.[]|select(.status=="ok")|.name'  */solvers.json | wc -l)
        echo '{"stable": '${COUNT}'}' > counter.json
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: counter.json
        path: counter.json
