name: docker-push
on:
    push:
        branches:
            - master

jobs:
    docker-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v1
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.before }}
            - run: python satex.py list > list.old
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.after }}
                  clean: false
            - run: python satex.py list > list.new
            - name: diff
              run: |
                python -c "new=set(open('list.new').read().splitlines());old=set(open('list.old').read().splitlines());print(' '.join(new.difference(old)),end='')" > list.diff
                echo ::set-env name=HAS_CHANGES::`test -s list.diff && echo 1 || echo 0`
            - name: Login to docker hub
              if: env.HAS_CHANGES == 1
              uses: actions-hub/docker/login@master
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - name:  build and push
              if: env.HAS_CHANGES == 1
              run: |
                set -ex
                cat list.diff
                for x in `cat list.diff`; do
                    python satex.py build $x
                    python satex.py push $x
                done
