name: docker-push
on:
    push:
        branches:
            - master

jobs:
    docker-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v2
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.before }}
            - run: python satex.py list > list.old
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.after }}
                  clean: false
            - run: python satex.py list > list.new
            - name: diff
              run: |
                python -c "new=set(open('list.new').read().splitlines());old=set(open('list.old').read().splitlines());print(' '.join(new.difference(old)),end='')" > list.diff
                echo HAS_CHANGES=`test -s list.diff && echo 1 || echo 0` >> $GITHUB_ENV
            - name:  build
              if: env.HAS_CHANGES == 1
              run: |
                set -ex
                cat list.diff
                for x in `cat list.diff`; do
                    python satex.py build $x
                done
            - name: DockerHub push
              if: env.HAS_CHANGES == 1
              run: |
                set -ex
                docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
                for x in `cat list.diff`; do
                    docker push satex/$x
                done
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - name: GH Package push
              if: env.HAS_CHANGES == 1
              run: |
                set -ex
                docker login https://docker.pkg.github.com -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
                for x in `cat list.diff`; do
                    docker tag satex/$x docker.pkg.github.com/sat-heritage/docker-images/$x
                    docker push docker.pkg.github.com/sat-heritage/docker-images/$x
                done
              env:
                  DOCKER_USERNAME: ${{ github.actor }}
                  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
