name: random-builds

on:
  schedule:
    - cron: "45 11 * * 1,3,5"

jobs:
    random-builds:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v2
            - uses: actions/checkout@v2
              with:
                  ref: master
            - run: python satex.py list | grep -v ':2018' | shuf | head -n 10 > list
            - name:  build-and-test
              run: |
                set -ex
                for x in `cat list`; do
                    python satex.py build $x
                    python satex.py test $x
                done
